use crate::command_args::*;
use crate::{
    command_spec, CommandSpec, EditorInput, EditorMarkInput, EditorSelection, OpenDocRuntimeProfile,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OpenDocCommand {
    CreateDocument(CreateDocumentArgs),
    CloseDocument,
    UndoCurrentEdit,
    RedoCurrentEdit,
    GetDocument,
    GetAuditView,
    SetDocumentTitle(SetDocumentTitleArgs),
    SetDocumentLocale(SetDocumentLocaleArgs),
    AddParagraph(AddParagraphArgs),
    RenderDocumentHtml,
    GetRuntimeProfile(OpenDocRuntimeProfile),
    GetRuntimeSession(GetRuntimeSessionArgs),
    AuthorizeRuntimeCommand(AuthorizeRuntimeCommandArgs),
    CreateRuntimeShareInvite(CreateRuntimeShareInviteArgs),
    RelayRuntimeSync(RelayRuntimeSyncArgs),
    ResolveRuntimeDocumentLookup(ResolveRuntimeDocumentLookupArgs),
    ImportGoogleDocsJson(ImportGoogleDocsJsonArgs),
    ImportDocOrDocxPath(ImportDocOrDocxPathArgs),
    ExportGoogleDocsJson,
    ImportGoogleSheetsJson(ImportGoogleSheetsJsonArgs),
    ExportGoogleSheetsJson,
    RenderWorkbookHtml(RenderWorkbookHtmlArgs),
    ImportDocxBase64(ImportDocxBase64Args),
    AddBinaryBlob(AddBinaryBlobArgs),
    SimulateShallowClone,
    UpdateBinaryBlobMetadata(UpdateBinaryBlobMetadataArgs),
    DeleteBinaryBlob(DeleteBinaryBlobArgs),
    RestoreBinaryBlob(RestoreBinaryBlobArgs),
    RecordBlobArchiveTombstone(RecordBlobArchiveTombstoneArgs),
    AddImageBlock(AddImageBlockArgs),
    InsertImageBlockAfter(InsertImageBlockAfterArgs),
    SignBlobWithOpenSshPrivateKey(SignBlobWithOpenSshPrivateKeyArgs),
    SignFastqBlobWithOpenSshPrivateKey(SignFastqBlobWithOpenSshPrivateKeyArgs),
    SignImagePixelsBlobWithOpenSshPrivateKey(SignImagePixelsBlobWithOpenSshPrivateKeyArgs),
    SignWithOpenSshPrivateKey(SignWithOpenSshPrivateKeyArgs),
    VerifyCurrentSignature(VerifyCurrentSignatureArgs),
    VerifyCurrentSignatures,
    SaveLocalRepository(RepositoryPathArgs),
    SaveLocalRepositoryOrCandidate(RepositoryPathArgs),
    SaveFlatRepository(RepositoryNamespaceArgs),
    SaveFlatRepositoryOrCandidate(RepositoryNamespaceArgs),
    SaveOpenDalFsRepository(RepositoryNamespaceArgs),
    SaveOpenDalFsRepositoryOrCandidate(RepositoryNamespaceArgs),
    AutosaveCurrentRepository,
    CompactLocalRepository(CompactLocalRepositoryArgs),
    OpenLocalRepository(RepositoryDocumentArgs),
    ScanLocalRepository(RepositoryPathArgs),
    OpenFlatRepository(RepositoryNamespaceDocumentArgs),
    OpenOpenDalFsRepository(RepositoryNamespaceDocumentArgs),
    MergeLocalRepositoryCandidates(RepositoryDocumentArgs),
    MergeFlatRepositoryCandidates(RepositoryNamespaceDocumentArgs),
    MergeOpenDalFsRepositoryCandidates(RepositoryNamespaceDocumentArgs),
    OpenLocalRepositoryByDoi(RepositoryDoiArgs),
    OpenFlatRepositoryByDoi(RepositoryNamespaceDoiArgs),
    OpenOpenDalFsRepositoryByDoi(RepositoryNamespaceDoiArgs),
    SetDocumentDoi(SetDocumentDoiArgs),
    InsertParagraphAfter(InsertParagraphAfterArgs),
    SplitParagraphAtInline(SplitParagraphAtInlineArgs),
    SplitParagraphAtTextOffset(SplitParagraphAtTextOffsetArgs),
    JoinParagraphWithPrevious(BlockIdArgs),
    DeleteBlock(BlockIdArgs),
    SetBlockTextStyle(SetBlockTextStyleArgs),
    SetEditorSelectionBlockStyle(SetEditorSelectionBlockStyleArgs),
    AddHeading(AddHeadingArgs),
    UpdateHeadingLevel(UpdateHeadingLevelArgs),
    AddLink(AddLinkArgs),
    InsertLinkAfter(InsertLinkAfterArgs),
    AddMention(AddMentionArgs),
    InsertMentionAfter(InsertMentionAfterArgs),
    AddFootnoteRef,
    InsertFootnoteRefAfter(InsertFootnoteRefAfterArgs),
    UpdateFootnoteBody(UpdateFootnoteBodyArgs),
    AddEquation(AddEquationArgs),
    InsertEquationAfter(InsertEquationAfterArgs),
    AddEquationBlock(AddEquationArgs),
    InsertEquationBlockAfter(InsertEquationBlockAfterArgs),
    AddListItem(AddListItemArgs),
    InsertListItemAfter(InsertListItemAfterArgs),
    UpdateListItem(UpdateListItemArgs),
    AdjustEditorSelectionListIndent(AdjustEditorSelectionListIndentArgs),
    InsertPageBreakAfter(AfterBlockArgs),
    AddPageBreak,
    InsertTableAfter(InsertTableAfterArgs),
    AddTable,
    AddTableRow(AddTableRowArgs),
    DeleteTableRow(DeleteTableRowArgs),
    AddTableCell(AddTableCellArgs),
    DeleteTableCell(DeleteTableCellArgs),
    AddCitation,
    InsertCitation(InsertCitationArgs),
    InsertCitationGroup(InsertCitationGroupArgs),
    InsertFootnoteCitationGroup(InsertFootnoteCitationGroupArgs),
    InsertFootnoteCitationAfter(InsertFootnoteCitationAfterArgs),
    UpdateCitationGroupItems(UpdateCitationGroupItemsArgs),
    SetCitationStyle(SetCitationStyleArgs),
    AddComment(AuthorBodyArgs),
    AddTextRangeComment(TextRangeAuthorBodyArgs),
    AddBlockComment(BlockAuthorBodyArgs),
    AddCommentReply(ThreadAuthorBodyArgs),
    DeleteCommentThread(ThreadIdArgs),
    RestoreCommentThread(ThreadIdArgs),
    DeleteComment(ThreadCommentIdArgs),
    RestoreComment(ThreadCommentIdArgs),
    UpdateComment(UpdateCommentArgs),
    AddSuggestion(AuthorTextArgs),
    AddTextRangeSuggestion(TextRangeAuthorTextArgs),
    AddBlockSuggestion(BlockAuthorTextArgs),
    AddDeleteSuggestion(DeleteSuggestionArgs),
    AddTextRangeDeleteSuggestion(TextRangeAuthorArgs),
    AddFormatSuggestion(FormatSuggestionArgs),
    AddTextRangeFormatSuggestion(TextRangeFormatSuggestionArgs),
    UpdateSuggestion(UpdateSuggestionArgs),
    AcceptSuggestion(AcceptSuggestionArgs),
    AcceptAllSuggestions(AcceptAllSuggestionsArgs),
    RejectSuggestion(RejectSuggestionArgs),
    RejectAllSuggestions(RejectAllSuggestionsArgs),
    DescribeEditorSelection(EditorSelection),
    SelectAllEditorContent,
    ApplyEditorInput(EditorInput),
    ApplyEditorMark(EditorMarkInput),
    AddBibliographyReference(BibliographyReferenceMetadataArgs),
    UpdateBibliographyReference(UpdateBibliographyReferenceArgs),
    UpdateBibliographyReferenceMetadata(UpdateBibliographyReferenceMetadataArgs),
    DeleteBibliographyReference(ReferenceIdArgs),
    RestoreBibliographyReference(ReferenceIdArgs),
    DeleteCitationGroup(CitationIdArgs),
    RestoreCitationGroup(CitationIdArgs),
    UpdateInlineText(InlineTextArgs),
    UpdateInlineEquationSource(InlineSourceArgs),
    UpdateMentionLabel(InlineLabelArgs),
    UpdateLinkHref(InlineHrefArgs),
    InsertInlineText(InsertInlineTextArgs),
    DeleteInline(InlineIdArgs),
    AddTextMark(TextMarkArgs),
    AddTextMarkRange(TextMarkRangeArgs),
    RemoveTextMark(TextMarkArgs),
    RemoveTextMarkRange(TextMarkRangeArgs),
    UpdateBlockEquationSource(BlockSourceArgs),
    UpdateImageAltText(BlockAltTextArgs),
    UpdateImageBlobHash(BlockBlobHashArgs),
    DescribeSpreadsheetSelection(SpreadsheetSelectionArgs),
    ReduceSpreadsheetSelection(SpreadsheetSelectionActionArgs),
    CopySpreadsheetSelectionTsv(SpreadsheetSelectionArgs),
    PasteSpreadsheetTsv(SpreadsheetPasteTsvArgs),
    ClearSpreadsheetSelection(SpreadsheetSelectionArgs),
    SetSpreadsheetSelectionFormat(SpreadsheetSelectionFormatArgs),
    AddSpreadsheetRowAfterSelection(SpreadsheetSelectionArgs),
    AddSpreadsheetColumnAfterSelection(SpreadsheetSelectionArgs),
    DeleteSpreadsheetSelectionRow(SpreadsheetSelectionArgs),
    DeleteSpreadsheetSelectionColumn(SpreadsheetSelectionArgs),
    MergeSpreadsheetSelection(SpreadsheetSelectionArgs),
    FreezeSpreadsheetSelection(SpreadsheetSelectionArgs),
    SetSpreadsheetSelectionFilter(SpreadsheetSelectionArgs),
    SetSpreadsheetWorkbookMetadata(SpreadsheetWorkbookMetadataArgs),
    SetSpreadsheetCell(SpreadsheetCellArgs),
    SetSpreadsheetCells(SpreadsheetCellEditsArgs),
    AddSpreadsheetSheet(SheetTitleArgs),
    RenameSpreadsheetSheet(SheetRenameArgs),
    DeleteSpreadsheetSheet(SheetIdArgs),
    RestoreSpreadsheetSheet(SheetIdArgs),
    AddSpreadsheetRow(SheetRowArgs),
    DeleteSpreadsheetRow(SheetRowArgs),
    RestoreSpreadsheetRow(SheetRowArgs),
    AddSpreadsheetColumn(SheetColumnArgs),
    DeleteSpreadsheetColumn(SheetColumnArgs),
    RestoreSpreadsheetColumn(SheetColumnArgs),
    AddSpreadsheetCellComment(CellCommentCreateArgs),
    UpdateSpreadsheetCellComment(CellCommentUpdateArgs),
    DeleteSpreadsheetCellComment(CellCommentIdArgs),
    RestoreSpreadsheetCellComment(CellCommentIdArgs),
    SetSpreadsheetFrozenAxes(FrozenAxesArgs),
    SetSpreadsheetCellValidation(CellValidationArgs),
    ClearSpreadsheetCellValidation(SheetAddressArgs),
    RestoreSpreadsheetCellValidation(SheetAddressArgs),
    MergeSpreadsheetCells(SheetRangeArgs),
    UnmergeSpreadsheetCells(SheetRangeArgs),
    RestoreSpreadsheetMerge(SheetRangeArgs),
    SetSpreadsheetBasicFilter(SheetRangeArgs),
    SetSpreadsheetBasicFilterOptions(FilterOptionsArgs),
    ClearSpreadsheetBasicFilter(SheetIdArgs),
    RestoreSpreadsheetBasicFilter(SheetIdArgs),
    AddSpreadsheetProtectedRange(ProtectedRangeArgs),
    UpdateSpreadsheetProtectedRange(ProtectedRangeArgs),
    DeleteSpreadsheetProtectedRange(SheetRangeArgs),
    RestoreSpreadsheetProtectedRange(SheetRangeArgs),
    SetSpreadsheetCellInSheet(SheetCellArgs),
    SetSpreadsheetCellsInSheet(SheetCellEditsArgs),
    SetSpreadsheetCellFormat(CellFormatArgs),
    SetSpreadsheetRowHeight(SheetRowHeightArgs),
    SetSpreadsheetColumnWidth(SheetColumnWidthArgs),
    CopySpreadsheetRange(CopyRangeArgs),
    AddSpreadsheetNamedRange(NamedRangeArgs),
    UpdateSpreadsheetNamedRange(NamedRangeArgs),
    DeleteSpreadsheetNamedRange(NamedRangeNameArgs),
    RestoreSpreadsheetNamedRange(NamedRangeNameArgs),
}

impl OpenDocCommand {
    pub fn name(&self) -> &'static str {
        match self {
            Self::CreateDocument(..) => "create_document",
            Self::CloseDocument => "close_document",
            Self::UndoCurrentEdit => "undo_current_edit",
            Self::RedoCurrentEdit => "redo_current_edit",
            Self::GetDocument => "get_document",
            Self::GetAuditView => "get_audit_view",
            Self::SetDocumentTitle(..) => "set_document_title",
            Self::SetDocumentLocale(..) => "set_document_locale",
            Self::AddParagraph(..) => "add_paragraph",
            Self::RenderDocumentHtml => "render_document_html",
            Self::GetRuntimeProfile(..) => "get_runtime_profile",
            Self::GetRuntimeSession(..) => "get_runtime_session",
            Self::AuthorizeRuntimeCommand(..) => "authorize_runtime_command",
            Self::CreateRuntimeShareInvite(..) => "create_runtime_share_invite",
            Self::RelayRuntimeSync(..) => "relay_runtime_sync",
            Self::ResolveRuntimeDocumentLookup(..) => "resolve_runtime_document_lookup",
            Self::ImportGoogleDocsJson(..) => "import_google_docs_json",
            Self::ImportDocOrDocxPath(..) => "import_doc_or_docx_path",
            Self::ExportGoogleDocsJson => "export_google_docs_json",
            Self::ImportGoogleSheetsJson(..) => "import_google_sheets_json",
            Self::ExportGoogleSheetsJson => "export_google_sheets_json",
            Self::RenderWorkbookHtml(..) => "render_workbook_html",
            Self::ImportDocxBase64(..) => "import_docx_base64",
            Self::AddBinaryBlob(..) => "add_binary_blob",
            Self::SimulateShallowClone => "simulate_shallow_clone",
            Self::UpdateBinaryBlobMetadata(..) => "update_binary_blob_metadata",
            Self::DeleteBinaryBlob(..) => "delete_binary_blob",
            Self::RestoreBinaryBlob(..) => "restore_binary_blob",
            Self::RecordBlobArchiveTombstone(..) => "record_blob_archive_tombstone",
            Self::AddImageBlock(..) => "add_image_block",
            Self::InsertImageBlockAfter(..) => "insert_image_block_after",
            Self::SignBlobWithOpenSshPrivateKey(..) => "sign_blob_with_openssh_private_key",
            Self::SignFastqBlobWithOpenSshPrivateKey(..) => {
                "sign_fastq_blob_with_openssh_private_key"
            }
            Self::SignImagePixelsBlobWithOpenSshPrivateKey(..) => {
                "sign_image_pixels_blob_with_openssh_private_key"
            }
            Self::SignWithOpenSshPrivateKey(..) => "sign_with_openssh_private_key",
            Self::VerifyCurrentSignature(..) => "verify_current_signature",
            Self::VerifyCurrentSignatures => "verify_current_signatures",
            Self::SaveLocalRepository(..) => "save_local_repository",
            Self::SaveLocalRepositoryOrCandidate(..) => "save_local_repository_or_candidate",
            Self::SaveFlatRepository(..) => "save_flat_repository",
            Self::SaveFlatRepositoryOrCandidate(..) => "save_flat_repository_or_candidate",
            Self::SaveOpenDalFsRepository(..) => "save_opendal_fs_repository",
            Self::SaveOpenDalFsRepositoryOrCandidate(..) => {
                "save_opendal_fs_repository_or_candidate"
            }
            Self::AutosaveCurrentRepository => "autosave_current_repository",
            Self::CompactLocalRepository(..) => "compact_local_repository",
            Self::OpenLocalRepository(..) => "open_local_repository",
            Self::ScanLocalRepository(..) => "scan_local_repository",
            Self::OpenFlatRepository(..) => "open_flat_repository",
            Self::OpenOpenDalFsRepository(..) => "open_opendal_fs_repository",
            Self::MergeLocalRepositoryCandidates(..) => "merge_local_repository_candidates",
            Self::MergeFlatRepositoryCandidates(..) => "merge_flat_repository_candidates",
            Self::MergeOpenDalFsRepositoryCandidates(..) => {
                "merge_opendal_fs_repository_candidates"
            }
            Self::OpenLocalRepositoryByDoi(..) => "open_local_repository_by_doi",
            Self::OpenFlatRepositoryByDoi(..) => "open_flat_repository_by_doi",
            Self::OpenOpenDalFsRepositoryByDoi(..) => "open_opendal_fs_repository_by_doi",
            Self::SetDocumentDoi(..) => "set_document_doi",
            Self::InsertParagraphAfter(..) => "insert_paragraph_after",
            Self::SplitParagraphAtInline(..) => "split_paragraph_at_inline",
            Self::SplitParagraphAtTextOffset(..) => "split_paragraph_at_text_offset",
            Self::JoinParagraphWithPrevious(..) => "join_paragraph_with_previous",
            Self::DeleteBlock(..) => "delete_block",
            Self::SetBlockTextStyle(..) => "set_block_text_style",
            Self::SetEditorSelectionBlockStyle(..) => "set_editor_selection_block_style",
            Self::AddHeading(..) => "add_heading",
            Self::UpdateHeadingLevel(..) => "update_heading_level",
            Self::AddLink(..) => "add_link",
            Self::InsertLinkAfter(..) => "insert_link_after",
            Self::AddMention(..) => "add_mention",
            Self::InsertMentionAfter(..) => "insert_mention_after",
            Self::AddFootnoteRef => "add_footnote_ref",
            Self::InsertFootnoteRefAfter(..) => "insert_footnote_ref_after",
            Self::UpdateFootnoteBody(..) => "update_footnote_body",
            Self::AddEquation(..) => "add_equation",
            Self::InsertEquationAfter(..) => "insert_equation_after",
            Self::AddEquationBlock(..) => "add_equation_block",
            Self::InsertEquationBlockAfter(..) => "insert_equation_block_after",
            Self::AddListItem(..) => "add_list_item",
            Self::InsertListItemAfter(..) => "insert_list_item_after",
            Self::UpdateListItem(..) => "update_list_item",
            Self::AdjustEditorSelectionListIndent(..) => "adjust_editor_selection_list_indent",
            Self::InsertPageBreakAfter(..) => "insert_page_break_after",
            Self::AddPageBreak => "add_page_break",
            Self::InsertTableAfter(..) => "insert_table_after",
            Self::AddTable => "add_table",
            Self::AddTableRow(..) => "add_table_row",
            Self::DeleteTableRow(..) => "delete_table_row",
            Self::AddTableCell(..) => "add_table_cell",
            Self::DeleteTableCell(..) => "delete_table_cell",
            Self::AddCitation => "add_citation",
            Self::InsertCitation(..) => "insert_citation",
            Self::InsertCitationGroup(..) => "insert_citation_group",
            Self::InsertFootnoteCitationGroup(..) => "insert_footnote_citation_group",
            Self::InsertFootnoteCitationAfter(..) => "insert_footnote_citation_after",
            Self::UpdateCitationGroupItems(..) => "update_citation_group_items",
            Self::SetCitationStyle(..) => "set_citation_style",
            Self::AddComment(..) => "add_comment",
            Self::AddTextRangeComment(..) => "add_text_range_comment",
            Self::AddBlockComment(..) => "add_block_comment",
            Self::AddCommentReply(..) => "add_comment_reply",
            Self::DeleteCommentThread(..) => "delete_comment_thread",
            Self::RestoreCommentThread(..) => "restore_comment_thread",
            Self::DeleteComment(..) => "delete_comment",
            Self::RestoreComment(..) => "restore_comment",
            Self::UpdateComment(..) => "update_comment",
            Self::AddSuggestion(..) => "add_suggestion",
            Self::AddTextRangeSuggestion(..) => "add_text_range_suggestion",
            Self::AddBlockSuggestion(..) => "add_block_suggestion",
            Self::AddDeleteSuggestion(..) => "add_delete_suggestion",
            Self::AddTextRangeDeleteSuggestion(..) => "add_text_range_delete_suggestion",
            Self::AddFormatSuggestion(..) => "add_format_suggestion",
            Self::AddTextRangeFormatSuggestion(..) => "add_text_range_format_suggestion",
            Self::UpdateSuggestion(..) => "update_suggestion",
            Self::AcceptSuggestion(..) => "accept_suggestion",
            Self::AcceptAllSuggestions(..) => "accept_all_suggestions",
            Self::RejectSuggestion(..) => "reject_suggestion",
            Self::RejectAllSuggestions(..) => "reject_all_suggestions",
            Self::DescribeEditorSelection(..) => "describe_editor_selection",
            Self::SelectAllEditorContent => "select_all_editor_content",
            Self::ApplyEditorInput(..) => "apply_editor_input",
            Self::ApplyEditorMark(..) => "apply_editor_mark",
            Self::AddBibliographyReference(..) => "add_bibliography_reference",
            Self::UpdateBibliographyReference(..) => "update_bibliography_reference",
            Self::UpdateBibliographyReferenceMetadata(..) => {
                "update_bibliography_reference_metadata"
            }
            Self::DeleteBibliographyReference(..) => "delete_bibliography_reference",
            Self::RestoreBibliographyReference(..) => "restore_bibliography_reference",
            Self::DeleteCitationGroup(..) => "delete_citation_group",
            Self::RestoreCitationGroup(..) => "restore_citation_group",
            Self::UpdateInlineText(..) => "update_inline_text",
            Self::UpdateInlineEquationSource(..) => "update_inline_equation_source",
            Self::UpdateMentionLabel(..) => "update_mention_label",
            Self::UpdateLinkHref(..) => "update_link_href",
            Self::InsertInlineText(..) => "insert_inline_text",
            Self::DeleteInline(..) => "delete_inline",
            Self::AddTextMark(..) => "add_text_mark",
            Self::AddTextMarkRange(..) => "add_text_mark_range",
            Self::RemoveTextMark(..) => "remove_text_mark",
            Self::RemoveTextMarkRange(..) => "remove_text_mark_range",
            Self::UpdateBlockEquationSource(..) => "update_block_equation_source",
            Self::UpdateImageAltText(..) => "update_image_alt_text",
            Self::UpdateImageBlobHash(..) => "update_image_blob_hash",
            Self::DescribeSpreadsheetSelection(..) => "describe_spreadsheet_selection",
            Self::ReduceSpreadsheetSelection(..) => "reduce_spreadsheet_selection",
            Self::CopySpreadsheetSelectionTsv(..) => "copy_spreadsheet_selection_tsv",
            Self::PasteSpreadsheetTsv(..) => "paste_spreadsheet_tsv",
            Self::ClearSpreadsheetSelection(..) => "clear_spreadsheet_selection",
            Self::SetSpreadsheetSelectionFormat(..) => "set_spreadsheet_selection_format",
            Self::AddSpreadsheetRowAfterSelection(..) => "add_spreadsheet_row_after_selection",
            Self::AddSpreadsheetColumnAfterSelection(..) => {
                "add_spreadsheet_column_after_selection"
            }
            Self::DeleteSpreadsheetSelectionRow(..) => "delete_spreadsheet_selection_row",
            Self::DeleteSpreadsheetSelectionColumn(..) => "delete_spreadsheet_selection_column",
            Self::MergeSpreadsheetSelection(..) => "merge_spreadsheet_selection",
            Self::FreezeSpreadsheetSelection(..) => "freeze_spreadsheet_selection",
            Self::SetSpreadsheetSelectionFilter(..) => "set_spreadsheet_selection_filter",
            Self::SetSpreadsheetWorkbookMetadata(..) => "set_spreadsheet_workbook_metadata",
            Self::SetSpreadsheetCell(..) => "set_spreadsheet_cell",
            Self::SetSpreadsheetCells(..) => "set_spreadsheet_cells",
            Self::AddSpreadsheetSheet(..) => "add_spreadsheet_sheet",
            Self::RenameSpreadsheetSheet(..) => "rename_spreadsheet_sheet",
            Self::DeleteSpreadsheetSheet(..) => "delete_spreadsheet_sheet",
            Self::RestoreSpreadsheetSheet(..) => "restore_spreadsheet_sheet",
            Self::AddSpreadsheetRow(..) => "add_spreadsheet_row",
            Self::DeleteSpreadsheetRow(..) => "delete_spreadsheet_row",
            Self::RestoreSpreadsheetRow(..) => "restore_spreadsheet_row",
            Self::AddSpreadsheetColumn(..) => "add_spreadsheet_column",
            Self::DeleteSpreadsheetColumn(..) => "delete_spreadsheet_column",
            Self::RestoreSpreadsheetColumn(..) => "restore_spreadsheet_column",
            Self::AddSpreadsheetCellComment(..) => "add_spreadsheet_cell_comment",
            Self::UpdateSpreadsheetCellComment(..) => "update_spreadsheet_cell_comment",
            Self::DeleteSpreadsheetCellComment(..) => "delete_spreadsheet_cell_comment",
            Self::RestoreSpreadsheetCellComment(..) => "restore_spreadsheet_cell_comment",
            Self::SetSpreadsheetFrozenAxes(..) => "set_spreadsheet_frozen_axes",
            Self::SetSpreadsheetCellValidation(..) => "set_spreadsheet_cell_validation",
            Self::ClearSpreadsheetCellValidation(..) => "clear_spreadsheet_cell_validation",
            Self::RestoreSpreadsheetCellValidation(..) => "restore_spreadsheet_cell_validation",
            Self::MergeSpreadsheetCells(..) => "merge_spreadsheet_cells",
            Self::UnmergeSpreadsheetCells(..) => "unmerge_spreadsheet_cells",
            Self::RestoreSpreadsheetMerge(..) => "restore_spreadsheet_merge",
            Self::SetSpreadsheetBasicFilter(..) => "set_spreadsheet_basic_filter",
            Self::SetSpreadsheetBasicFilterOptions(..) => "set_spreadsheet_basic_filter_options",
            Self::ClearSpreadsheetBasicFilter(..) => "clear_spreadsheet_basic_filter",
            Self::RestoreSpreadsheetBasicFilter(..) => "restore_spreadsheet_basic_filter",
            Self::AddSpreadsheetProtectedRange(..) => "add_spreadsheet_protected_range",
            Self::UpdateSpreadsheetProtectedRange(..) => "update_spreadsheet_protected_range",
            Self::DeleteSpreadsheetProtectedRange(..) => "delete_spreadsheet_protected_range",
            Self::RestoreSpreadsheetProtectedRange(..) => "restore_spreadsheet_protected_range",
            Self::SetSpreadsheetCellInSheet(..) => "set_spreadsheet_cell_in_sheet",
            Self::SetSpreadsheetCellsInSheet(..) => "set_spreadsheet_cells_in_sheet",
            Self::SetSpreadsheetCellFormat(..) => "set_spreadsheet_cell_format",
            Self::SetSpreadsheetRowHeight(..) => "set_spreadsheet_row_height",
            Self::SetSpreadsheetColumnWidth(..) => "set_spreadsheet_column_width",
            Self::CopySpreadsheetRange(..) => "copy_spreadsheet_range",
            Self::AddSpreadsheetNamedRange(..) => "add_spreadsheet_named_range",
            Self::UpdateSpreadsheetNamedRange(..) => "update_spreadsheet_named_range",
            Self::DeleteSpreadsheetNamedRange(..) => "delete_spreadsheet_named_range",
            Self::RestoreSpreadsheetNamedRange(..) => "restore_spreadsheet_named_range",
        }
    }

    pub fn spec(&self) -> &'static CommandSpec {
        command_spec(self.name())
            .unwrap_or_else(|| panic!("missing command metadata for {}", self.name()))
    }
}
