export type {
  AuditCommandName,
  AuthorizationCommandName,
  CommandArgs,
  CommandResult,
  DesktopCommandArgs,
  DesktopCommandName,
  DocumentCommandName,
  EditorCommandName,
  RuntimeLookupCommandName,
  RuntimeProfileCommandName,
  RuntimeSessionCommandName,
  ShareInviteCommandName,
  SpreadsheetCellEdit,
  SyncRelayCommandName,
  TextCommandName,
} from "./generated/commands";
